### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by lfittl** [showplan/azure-data-studio-queryplan-show#6]
This seems to be a great example of an Azure Data Studio extension (found it via the Azure blog)

However, it seems that there is currently no LICENSE file, or license thats declared otherwise.

Is this repository available under an open-source license? Thanks!

**Comment by phil-scott-78** [comment]
Thanks for the heads up, missed this in the reorganization and I've been traveling of late. It's been added (MIT)
